### ISSUE TITLE
Spin up API

### ISSUE THREAD

**Issue by Burwin** [BambooSoftwareLLC/stay-in-touch#1]
# Summary
Get the barebones of the API created and hosted on Google Cloud.

# Tasks
- [x] Spin up a blank template NestJS API
- [ ] Dockerize it (watch out for caching)
- [ ] Deploy to Google Cloud Run
- [ ] Make sure automated deployments to Google Cloud setup (deploy all branches with pattern `api/release/xxx`)
